### ISSUE TITLE
Multiple BWB repositories

### ISSUE THREAD

**Issue by christophe-riolo** [sunyata-zero-archived/buddhist-well-being-prototype-4#1]
Hej! 
I had read that you were looking for help some time ago, and started developing on BWB, even submitted a pull request, but today I see that you have made several repositories. This is slightly confusing and I am not sure where to commit anymore. Why not use branches on only one repository?

**Comment by SunyataZero** [comment]
Hi, sorry for the late reply, i didn't get a notification email for this issue, not sure why but i am in the process now of cleaning up the repositories that i have. The reason for multiple repos is just that i'm not used to git and that they are somewhat different from each other, but maybe having multiple branches instead would be better even if the changes are large. Kind Regards, Tord
PS I have changed the notification settings for github, but in case this doesn't work you can reach me at tord (dot) dellsen (at) protonmail (dot) com

**Comment by SunyataZero** [comment]
@christophe-riolo I don't know if this helps with notifications but i'm adding your name here just in case. (For myself i think i managed to fix the settings so that i get emails automatically when there are comments, at least on pull requests and probably on issues as well)

I think i will put a link at the top of all "bwb" repos to the new well-being-diary repo instead, (after this is done i will close this issue)

**Comment by SunyataZero** [comment]
@christophe-riolo Hi, i'm trying to invite you to the gitter chat for the "well-being diary" repo but cannot find your email address, would you be willing to send it to me? My email is tord (dot) dellsen (at) protonmail (dot) com
